# Generated by Django 5.1.7 on 2025-03-16 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_discount_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_discount_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showtime',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='student_price',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='theater',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='theater',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='theater',
            name='has_3d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theater',
            name='has_imax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theater',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theater',
            name='is_accessible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_theaters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theater',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='theater',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='theater',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='theater',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
