# Generated by Django 5.1.7 on 2025-05-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_notes_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_time']},
        ),
        migrations.AlterModelOptions(
            name='theater',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='theater',
            name='description',
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='theater',
            name='total_seats',
            field=models.PositiveIntegerField(default=48),
        ),
    ]
