# Generated by Django 5.1.7 on 2025-05-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_theater_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='theater',
            options={},
        ),
        migrations.AddField(
            model_name='theater',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='theater',
            name='total_seats',
            field=models.IntegerField(default=48),
        ),
    ]
